### ISSUE TITLE
AttributeError: 'PW3D' object has no attribute 'oks'

### ISSUE THREAD

**Issue by ocissor** [YangChangHee/ICCV2023_SEFD_RELEASE#10]
Hi, in the PW3D.py line 159 generates the above error. Can you explain what does **oks** stand for, and to get rid of the error should I just comment this line.

Thank you

**Comment by YangChangHee** [comment]
I apologize for the delay. 
The Object Keypoint Similarity (OKS) you mentioned refers to the keypoint similarity used in human pose estimation when calculating MSCOCO mAP. 
We inserted this code to test the difference between the OKS of OpenPose used in testing and the real ground truth (GT). It's a test code to see how much difference there is. So, you can simply delete it and proceed. 
Thank you. :) 
(I have made the code modifications).

**Comment by ocissor** [comment]
thank you!
