### ISSUE TITLE
what does augmentation_together function do?

### ISSUE THREAD

**Issue by ocissor** [YangChangHee/ICCV2023_SEFD_RELEASE#11]
Hi, there is a function in **common/utils/preprocessing.py named augmentation_together**. I am struggling to understand what this function does. Would you be kind enough to explain it?

Thank you

**Comment by YangChangHee** [comment]
"The code named 'augmentation_together' in the file 'common/utils/preprocessing.py' was created to make the preprocessed image(e.g. SMPL Edge, EPS, ...), input image, and augmentation the same. This was written because augmentation is carried out randomly in a training situation."

**Comment by ocissor** [comment]
Thank you!
