### ISSUE TITLE
ModuleNotFoundError: No module named 'losses' and ModuleNotFoundError: No module named 'ops'

### ISSUE THREAD

**Issue by ocissor** [YangChangHee/ICCV2023_SEFD_RELEASE#7]
Hi,
In model copy.py line 14 - from losses import camera_fitting_loss, body_fitting_loss - generates the above error. Can you please share the losses.py file?

The other error arises from pidinet_config.py-line2. I think this is because of another missing file.

Thank you!

**Comment by YangChangHee** [comment]
Thank you for identifying the error! I have uploaded the file for 'ops.py,' and you can find it in the main folder. Additionally, please disregard the 'camera_fitting_loss' and 'body_fitting_loss' in 'losses.py' as they were added during the use of SMPLify and have been removed.
I have also completed the update. Thank you :)
